name : Dhruvesh Patel
title: All things facinating
markdown: kramdown
theme: minima
email: dhruvdplayer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Dhruvesh Patel.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dhruvdplayer
linkedin_username: dhruveshp
disqus:
   shortname: dhruvdplayer-github-personal
plugins:
  - jekyll-feed 
  - jekyll-sitemap
  - jekyll-seo-tag
